---
deployment:
  tasks:
    - source /home/lmp723c7ts05/virtualenv/cyberflaxlabs/3.7/bin/activate && cd /home/lmp723c7ts05/cyberflaxlabs
    - pip install -r requirements.txt
    - python manage.py collectstatic --no-input
    - python manage.py migrate