# Generated by Django 3.2 on 2021-09-07 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ourwork_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectimage', models.FileField(blank=True, upload_to='ourwork/projectimage')),
                ('projecticon', models.FileField(blank=True, upload_to='ourwork/projecticon')),
                ('projectTitle', models.CharField(blank=True, max_length=200)),
                ('content', models.CharField(blank=True, max_length=5000)),
                ('projectsource', models.FileField(blank=True, upload_to='ourwork/projectsource')),
                ('sourceLink', models.CharField(blank=True, max_length=500)),
                ('projectsource1', models.FileField(blank=True, upload_to='ourwork/projectsource')),
                ('sourceLink1', models.CharField(blank=True, max_length=500)),
                ('projectlink', models.CharField(blank=True, max_length=500)),
                ('catagory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ourwork.ourwork_cat')),
            ],
        ),
        migrations.CreateModel(
            name='headbanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=5000)),
                ('projecticon', models.ImageField(upload_to='ourwork/projecticon')),
                ('projectimage', models.ImageField(upload_to='ourwork/projectimage')),
                ('projectTitle', models.CharField(max_length=200)),
                ('projectsource', models.ImageField(upload_to='ourwork/projectsource')),
                ('sourceLink', models.CharField(max_length=500)),
                ('projectlink', models.CharField(blank=True, max_length=500)),
                ('catagory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ourwork.ourwork_cat')),
            ],
        ),
    ]
