# Generated by Django 3.2 on 2021-09-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourwork_cat',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
