# Generated by Django 3.2 on 2021-09-25 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourwork', '0002_ourwork_cat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headbanner',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='headbanner', to='ourwork.ourwork_cat'),
        ),
    ]
