# Generated by Django 3.2 on 2021-09-08 09:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_content', ckeditor.fields.RichTextField()),
                ('blog_time', models.DateTimeField(auto_now=True)),
                ('blog_share', models.IntegerField(default=0)),
                ('blog_views', models.IntegerField(default=0)),
                ('blog_owners', models.CharField(max_length=50)),
                ('blog_image', models.ImageField(default='', upload_to='wesiteblog/images')),
                ('blog_catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.catagory')),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_content', ckeditor.fields.RichTextField()),
                ('blog_time', models.DateTimeField(auto_now=True)),
                ('blog_share', models.IntegerField(default=0)),
                ('blog_views', models.IntegerField(default=0)),
                ('blog_owner', models.CharField(max_length=50)),
                ('blog_image', models.ImageField(default='', upload_to='wesiteblog/images')),
                ('blog_catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.catagory')),
            ],
        ),
    ]
