# Generated by Django 3.2 on 2021-09-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[('1', 'blog'), ('2', 'news')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
