# Generated by Django 3.2 on 2021-09-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogviews',
            old_name='blog',
            new_name='blogid',
        ),
        migrations.AlterUniqueTogether(
            name='blogviews',
            unique_together={('blogid', 'ip')},
        ),
    ]
