# Generated by Django 3.2 on 2021-09-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210908_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogviews',
            name='type',
            field=models.CharField(default='v', max_length=2),
            preserve_default=False,
        ),
    ]
