# Generated by Django 3.2 on 2021-09-25 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(default='', upload_to='media/ourwork')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Submenu', models.CharField(max_length=50)),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServiceSubMenu', to='service.service')),
            ],
        ),
        migrations.CreateModel(
            name='WhatWeDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(default='', upload_to='media/whatwedo')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('services', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('subservices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicesubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='subservices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=500)),
                ('tag_content', models.CharField(max_length=5000)),
                ('Optionalicon', models.FileField(blank=True, upload_to='media/subservice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicesubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='subproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='media/subproject')),
                ('name', models.CharField(max_length=50)),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicesubmenu')),
                ('services', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
        migrations.CreateModel(
            name='sub_serviceWeOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(default='', upload_to='media/serviceoffer')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('services', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('subservices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicesubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='sub_expertise_icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(default='', upload_to='media/subexpertise')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('services', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('subservices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicesubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='sub_expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.CharField(max_length=500)),
                ('services', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('subservices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicesubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='sub_benifit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(default='', upload_to='media/fact')),
                ('content', models.CharField(max_length=500)),
                ('services', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('subservices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicesubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='serviceFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(default='', upload_to='media/fact')),
                ('content', models.CharField(max_length=500)),
                ('services', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('subservices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicesubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='middleimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(default='', upload_to='media/middle')),
                ('services', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('subservices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicesubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='headbanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(default='', upload_to='media/subservice')),
                ('banner_icon', models.ImageField(default='', upload_to='media/subservice')),
                ('banner_title', models.CharField(max_length=100)),
                ('banner_content', models.CharField(max_length=500)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicesubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='expertiseWithTitleIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(default='', upload_to='media/expertise')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(blank=True, max_length=5000)),
                ('services', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('subservices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicesubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('expertise', models.CharField(blank=True, max_length=500)),
                ('Select_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicesubmenu')),
                ('services', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
        migrations.CreateModel(
            name='engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=5000)),
                ('icon', models.FileField(default='', upload_to='media/fact')),
                ('services', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('subservices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicesubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='devLifecycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=5000)),
                ('icon', models.FileField(default='', upload_to='media/fact')),
                ('services', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('subservices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicesubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='bottomdiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(default='', upload_to='media/middle')),
                ('content', models.CharField(max_length=5000)),
                ('services', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('subservices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicesubmenu')),
            ],
        ),
    ]
