# Generated by Django 3.2 on 2021-09-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='servicesubmenu',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
