# Generated by Django 3.2 on 2021-09-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210926_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesubmenu',
            old_name='Service',
            new_name='service',
        ),
    ]
